[package]
name = "karlsen-wrpc-example-subscriber"
description = "Karlsen wRPC subscription example"
publish = false
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
futures.workspace = true
karlsen-consensus-core.workspace = true
karlsen-rpc-core.workspace = true
karlsen-wrpc-client.workspace = true
karlsen-notify.workspace = true
tokio.workspace = true
workflow-core.workspace = true
workflow-log.workspace = true
ctrlc.workspace = true
